spring:
  application:
    name: inventory-management

  datasource:
    url: jdbc:postgresql://localhost:5432/inventory-management
    username: postgres
    password: 123456789

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: djlVQEprITNRI3haN3JGJGdXMWJUJWUySypOZFk4b0xwTSF6SHNWNFJjRSRCbkNtWHFTalV3QXlHdFBpTGRPIw==
  expiration: 86400000 # 24 giờ
